### ISSUE TITLE
5.4 statchek

### ISSUE THREAD

**Issue by akryukov39** [r-classes/2020_da4l_hw5#1]
При попытке провести тест t.test(data = corals, ScientificName ~ DepthInMeters) выдаёт
Ошибка в t.test.formula(data = corals, ScientificName ~ DepthInMeters) :
  группирующий фактор должен иметь в точности 2 уровня

Когда пытаюсь через запятую t.test(data = corals, ScientificName, DepthInMeters) пишет
Ошибка в t.test(data = corals, ScientificName, DepthInMeters) :
  объект 'ScientificName' не найден

**Comment by agricolamz** [comment]
А мне казалось, нужно хи-квадрат провести, а не т-тест...

**Comment by akryukov39** [comment]
> А мне казалось, нужно хи-квадрат провести, а не т-тест...

Действительно, только он что-то странное выдаёт, хотя вроде датасет отфильтровал правильно

```
coral_depth <- data.frame(select(corals[corals$ScientificName %in% c("Heteropolypus ritteri", "Lophelia pertusa"), ], ScientificName, DepthInMeters))
chisq.test(table(coral_depth), simulate.p.value = TRUE)

data:  table(coral_depth)
X-squared = 21827, df = NA, p-value = 0.0004998
```

**Comment by agricolamz** [comment]
Потому что хи-квадрат на вход принимает матрицы сопряженности или датафреймы такой же структуры. Например, 

chisq.test(matrix(c(10, 10, 10, 20), nrow = 2))
